### PR TITLE
New force models

### PR DESCRIPTION
**Pull request by sjcrs**
This adds several unmagnetized force models and tests to check these new models. Below are the comparisons of the force magnitudes calculated for a particular configuration compared to the force magnitudes calculated with an identical setup in Betacool. The "Unmagnetized" model actually contains two approximate methods, one with a cutoff value introduced for indefinite integrals, and the Binney approximation with further simplifying assumptions that take the Coulomb log out of the integral. 

image

### CODE REVIEW

**Comment by bruhwiler** [comment]
Looks like very nice work!
@ilyapogorelov -- could you please review the code before merging?

**Comment by sjcrs** [comment]
@ilyapogorelov It's been a while, but how would you like to review this? Want to dig into the source or have a phone call?  I think the un-magnetized models could be useful soon

**Comment by Agixi** [comment]
Hello

I was trying to reproduce those results, starting with Parkhomchuk's model. I used a new version of JSPEC (https://github.com/JeffersonLab/ElectronCooling). At the first plot is what I received. The shape is identical but there is a factor 10 of difference. 

jsec2_beta


I also checked the comparison for various values of input parameters and I find out a difference between results for more massive ions. Did you also observe this kind of behaviour? 

PB_temp

**Comment by sjcrs** [comment]
Hi @Agixi , 
Thanks for bringing this to my attention. This fork differs in the implementation from https://github.com/JeffersonLab/ElectronCooling for the friction forces. Did you observe these differences in both? They both read the same .in input files, so running with both forks is probably the first thing I'd check. 

I'd like to understand what's going on here so I can help and fix any potential bugs. Is it OK to keep corresponding via this pull request comment section, or would you like to correspond directly by email?

**Comment by Agixi** [comment]
Hi @sjcrs,

The results for both JSPEC versions seem to agree. I attached the plot with both of them. 
jspec_vs_beta

In this plot, I checked the behaviour for different longitudinal Temperatures.
Pb_T_l_comp

About the factor 10 of difference between our plots. I finally found an issue in input files and now my results agree with yours. Sorry for the unnecessary problem. 

We can communicate directly by email if it's fine for you.

**Comment by sjcrs** [comment]
@Agixi
 Hi, I'm glad you found a solution to your issue and I'm relieved to see that you found good agreement. I will try to configure this package so there is an issues tab for future bug reports. You can email me at coleman _at_ radiasoft.net if you have any trouble in the future.

**Pull request merged**
